/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Información de la API
         * @description Retorna información básica sobre la API y sus endpoints disponibles
         */
        get: operations["getApiInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Verifica el estado de la API y sus dependencias
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check (legacy endpoint)
         * @description Endpoint de compatibilidad para verificar el estado de la API
         */
        get: operations["getHealthLegacy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enviar mensaje al chatbot
         * @description Procesa un mensaje del usuario y retorna la respuesta del chatbot
         */
        post: operations["sendChatMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enviar mensaje al chatbot (legacy endpoint)
         * @description Endpoint de compatibilidad para procesar mensajes del chatbot
         */
        post: operations["sendChatMessageLegacy"];
        delete?: never;
        /**
         * CORS preflight para chat
         * @description Maneja preflight requests para CORS
         */
        options: operations["chatOptions"];
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiInfo: {
            /**
             * @description Nombre del servicio
             * @example Chatbot Demo API
             */
            service: string;
            /**
             * @description Versión de la API
             * @example 2.0.0
             */
            version: string;
            /**
             * @description Estado actual del servicio
             * @example running
             */
            status: string;
            /**
             * @description Entorno de ejecución
             * @example development
             * @enum {string}
             */
            environment: "development" | "staging" | "production";
            /** @description Endpoints disponibles */
            endpoints: {
                /** @example Chat with AI */
                "POST /chat.php"?: string;
                /** @example Health check */
                "GET /health.php"?: string;
                /** @example API information */
                "GET /"?: string;
            };
            /**
             * Format: date-time
             * @description Timestamp de la respuesta
             * @example 2025-09-15T22:58:19+00:00
             */
            timestamp: string;
        };
        ChatRequest: {
            /**
             * @description Mensaje del usuario para el chatbot
             * @example ¿Cuál es el propósito de este chatbot?
             */
            message: string;
        };
        ChatResponse: {
            /**
             * @description Indica si la operación fue exitosa
             * @example true
             */
            success: boolean;
            /**
             * @description Respuesta generada por el chatbot
             * @example Este chatbot está diseñado para ayudarte con información sobre el proyecto...
             */
            response: string;
            /**
             * Format: date-time
             * @description Timestamp de cuando se generó la respuesta
             * @example 2025-09-15T22:58:19+00:00
             */
            timestamp: string;
            /**
             * @description Modo de operación del chatbot
             * @example production
             * @enum {string}
             */
            mode?: "demo" | "production";
        };
        HealthResponse: {
            /**
             * @description Estado general del servicio
             * @example healthy
             */
            status: string;
            /**
             * @description Nombre del servicio
             * @example Chatbot Demo API
             */
            service: string;
            /**
             * @description Versión de la API
             * @example 2.0.0
             */
            version: string;
            /**
             * @description Entorno de ejecución
             * @example development
             * @enum {string}
             */
            environment: "development" | "staging" | "production";
            /**
             * Format: date-time
             * @description Timestamp del health check
             * @example 2025-09-15T22:58:19+00:00
             */
            timestamp: string;
            /**
             * @description Tiempo de actividad del servicio
             * @example 2d 5h 30m
             */
            uptime?: string;
            /** @description Verificaciones detalladas de componentes */
            checks?: {
                database?: components["schemas"]["ComponentCheck"];
                knowledge_base?: components["schemas"]["KnowledgeBaseCheck"];
                api_key?: components["schemas"]["ApiKeyCheck"];
            };
        };
        ComponentCheck: {
            /**
             * @description Estado del componente
             * @example healthy
             * @enum {string}
             */
            status: "healthy" | "degraded" | "unhealthy";
            /**
             * @description Ruta del componente verificado
             * @example /path/to/database.db
             */
            path?: string;
            /**
             * @description Si el recurso existe
             * @example true
             */
            exists?: boolean;
            /**
             * @description Si el recurso es escribible
             * @example true
             */
            writable?: boolean;
            /**
             * @description Mensaje de error si el componente falla
             * @example Connection timeout
             */
            error?: string;
        };
        KnowledgeBaseCheck: components["schemas"]["ComponentCheck"] & {
            /**
             * @description Número de archivos en la base de conocimiento
             * @example 5
             */
            files_count?: number;
            /**
             * @description Lista de archivos disponibles
             * @example [
             *       "intro.md",
             *       "features.md",
             *       "api.md"
             *     ]
             */
            files?: string[];
        };
        ApiKeyCheck: components["schemas"]["ComponentCheck"] & {
            /**
             * @description Modo de operación de la API key
             * @example production
             * @enum {string}
             */
            mode?: "demo" | "production";
            /**
             * @description Si la API key está configurada
             * @example true
             */
            configured?: boolean;
        };
        ApiError: {
            /**
             * @description Indica que ocurrió un error
             * @example true
             */
            error: boolean;
            /**
             * @description Código de estado HTTP
             * @example 500
             */
            status: number;
            /**
             * @description Mensaje de error para el usuario
             * @example Error interno del servidor
             */
            message: string;
            /**
             * Format: date-time
             * @description Timestamp del error
             * @example 2025-09-15T22:58:19+00:00
             */
            timestamp: string;
            /** @description Información de debugging (solo en desarrollo) */
            debug?: {
                /** @example RuntimeException */
                exception?: string;
                /** @example Database connection failed */
                message?: string;
                /** @example /path/to/file.php */
                file?: string;
                /** @example 42 */
                line?: number;
                /** @example Stack trace here... */
                trace?: string;
            };
        };
        ValidationError: components["schemas"]["ApiError"] & {
            /**
             * @description Lista de errores de validación específicos
             * @example [
             *       "Mensaje no puede estar vacío",
             *       "Mensaje demasiado largo"
             *     ]
             */
            errors?: string[];
        };
        RateLimitError: components["schemas"]["ApiError"] & {
            /**
             * @description Tiempo en segundos para el próximo intento
             * @example 60
             */
            retry_after?: number;
            /**
             * @description Límite de requests por ventana de tiempo
             * @example 50
             */
            limit?: number;
            /**
             * @description Requests restantes en la ventana actual
             * @example 0
             */
            remaining?: number;
        };
        ExternalServiceError: components["schemas"]["ApiError"] & {
            /**
             * @description Nombre del servicio externo que falló
             * @example Gemini
             */
            service?: string;
            /**
             * @description Código de estado del servicio externo
             * @example 503
             */
            service_status?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getApiInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Información de la API retornada exitosamente */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiInfo"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Estado de la API */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Error interno del servidor */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getHealthLegacy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Estado de la API */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    sendChatMessage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Respuesta del chatbot generada exitosamente */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Error de validación en el request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
            /** @description Rate limit excedido */
            429: {
                headers: {
                    /** @description Tiempo en segundos para el próximo intento */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitError"];
                };
            };
            /** @description Error interno del servidor */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Error del servicio externo (Gemini API) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalServiceError"];
                };
            };
        };
    };
    sendChatMessageLegacy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Respuesta del chatbot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
        };
    };
    chatOptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CORS headers aplicados */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
